eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8086/eureka/}
  instance:
    instance-id: karen-assistant-instance
spring:
  application:
    name: karen-assistant